{% extends "base.yml" %}
{% block description %}Global configuration file{% endblock %}
{% block content %}
# Project name
project_name: chip 

# The base scratch path that data, logs, etc... will be dumped to
scratch_dir: /scratch/

# Directories that will be searched for task yml files
task_dirs:
  #- path/to/task/dir

# Custom or misc lib files 
misc_libs:
  #- path/to/lib

# Custom or misc lef files 
misc_lefs:
  #- path/to/lef

# List of all standard cells that can be used
std_cells:
  #- name: example_name
  #  rtl: 
  #    - path/to/rtl
  #  libs_syn: 
  #    - path/to/lib/for/synthesis
  #  lefs:
  #    - path/to/lef
  #  cap_table_file: path/to/cap/table/file
  #  qrc_tech_file: path/to/qrc/tech/file # Takes precedence over cap table if supplied
{% endblock %}
